### ISSUE TITLE
Libreria de reportes

### ISSUE THREAD

**Issue by jriverarojas** [kplian/pxp#8]
Crear librería de reportes que permita generar código a partir de xml a TCPDF. Esta librería debe ser compatible con las ya existentes en el framework

**Comment by rensi4rn** [comment]
sera mejor trabajar en la integración con pentaho, por otro lado TCPDF permite hacer el reporte en HTML

**Comment by Chacho3x** [comment]
o.O ???

2016-03-03 16:16 GMT-04:00 Rensi Arteaga <notifications@github.com>:
